#:kivy 2.0.0
#:import Logger kivy.logger.Logger
<ManagerWindow>:
    AnchorLayout:
        anchor_x: "left"
        anchor_y: "top"
        GridLayout:
            size_hint: 1,None
            height: 25
            rows: 1
            Button:
                size_hint: (None,1)
                text: "Select Angband Folder"
            Button:
                size_hint: (None,1)
                text: "Export Gamedata Folder"
